# Generated by Django 5.1.1 on 2024-11-02 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0002_alter_patientdetails_doctor'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctormodel')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitalmodel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.patientmodel')),
            ],
        ),
    ]
