# Generated by Django 5.1.1 on 2024-11-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0005_merge_20241102_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(editable=False)),
                ('age', models.IntegerField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patientdetails')),
            ],
        ),
    ]
