# Generated by Django 5.1.1 on 2024-11-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetPatient',
        ),
    ]
