# Generated by Django 5.1.1 on 2024-11-02 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('specialization', models.CharField(choices=[('cardio', 'Cardiology'), ('dermo', 'Dermatology'), ('pedia', 'Pediatrics'), ('psy', 'Psychiatry'), ('other', 'Other')], max_length=10)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('location', models.TextField()),
                ('license_number', models.CharField(max_length=6)),
                ('doctors', models.ManyToManyField(related_name='hospitals', to='hospital.doctormodel')),
            ],
        ),
        migrations.DeleteModel(
            name='DoctorInfo',
        ),
        migrations.DeleteModel(
            name='PatiantInfo',
        ),
    ]
