# Generated by Django 5.1.1 on 2024-11-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctormodel_hospitalmodel_delete_doctorinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalmodel',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='hospitals', to='hospital.doctormodel'),
        ),
        migrations.AlterField(
            model_name='hospitalmodel',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
