# Generated by Django 5.1.1 on 2024-11-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_hospitalmodel_doctors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalmodel',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
