# Generated by Django 5.1.1 on 2024-11-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_hospitalmodel_phone_number'),
        ('hospital', '0004_remove_patientdetails_doctor'),
    ]

    operations = [
    ]
