# Generated by Django 5.1.1 on 2024-11-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_merge_20241102_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='token_number',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True),
        ),
    ]
