# Generated by Django 5.1.1 on 2024-11-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_patientdetails_token_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='token_number',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
